#!/usr/bin/env sh
# This file is part of libertine. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/libertine-linux/libertine/master/COPYRIGHT. No part of libertine, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2019 The developers of libertine. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/libertine-linux/libertine/master/COPYRIGHT.


set -e
set -u
set -f


program_name='install-homebrew'


_program_path_find()
{
	if [ "${0%/*}" = "$0" ]; then

		# We've been invoked by the interpreter as, say, bash program
		if [ -r "$0" ]; then
			pwd -P
		# Clutching at straws; probably run via a download, anonymous script, etc, weird execve, etc
		else
			printf '\n'
		fi

	else

		# We've been invoked with a relative or absolute path (also when invoked via PATH in a shell)

		_program_path_find_parentPath()
		{
			parentPath="${scriptPath%/*}"
			if [ -z "$parentPath" ]; then
				parentPath='/'
			fi
			cd "$parentPath" 1>/dev/null
		}

		# pdksh / mksh have problems with unsetting a variable that was never set...
		if [ "${CDPATH+set}" = 'set' ]; then
			unset CDPATH
		fi

		if command -v realpath 1>/dev/null 2>/dev/null; then
			(
				scriptPath="$(realpath "$0")"

				_program_path_find_parentPath
				pwd -P
			)
		elif command -v readlink 1>/dev/null 2>/dev/null; then
			(
				local recursionDepth=0
				_program_path_resolve_symlinks_recursively()
				{
					local unresolvedPath="$1"
					
					recursionDepth=$((recursionDepth + 1))
					
					if [ $recursionDepth -gt 10 ]; then
						printf '%s\n' 'Recursion to depths greater than 10 is not allowed when resolving links.'
						return 1
					fi
					
					local potentialLinkDestination="$(readlink -- "$unresolvedPath")"
					
					if [ -z "$potentialLinkDestination" ]; then
						scriptPath="$unresolvedPath"
						return 0
					fi
					local linkDestination="$potentialLinkDestination"
					local parentFolderPath="${unresolvedPath%/*}"
					
					if [ "$parentFolderPath" = "$unresolvedPath" ]; then
						_program_path_resolve_symlinks_recursively "$linkDestination"
					else
						case "$linkDestination" in
														
							/*)
								_program_path_resolve_symlinks_recursively "$linkDestination"
							;;
							
							*)
								_program_path_resolve_symlinks_recursively "$parentFolderPath"/"$linkDestination"
							;;
							
						esac
					fi
				}

				scriptPath="$0"
				_program_path_resolve_symlinks_recursively "$scriptPath"

				_program_path_find_parentPath
				pwd -P
			)
		else
			# This approach will fail in corner cases where the script itself is a symlink in a path not parallel with the concrete script
			(
				scriptPath="$0"

				_program_path_find_parentPath
				pwd -P
			)
		fi

	fi
}

fail()
{
	local message="$1"
	
	printf '%s:FAIL:%s\n' "$program_name" "$message" 1>&2
	exit 1
}

depends()
{
	local binary
	for binary in "$@"
	do
		if ! command -v "$binary" 1>/dev/null 2>/dev/null; then
			fail "The binary `$binary` is not on the PATH"
		fi
	done
}

install_homebrew_validateCommandLineArguments()
{
	case "$#" in

		0)
			:
		;;

		1)
			case "$1" in

				-h|--help)
					printf <<-EOF
						$program_name
						$program_name -h|--help
						
						Installs a homebrew environment for macos.
						
						Specify the environment variable 'homebrew_configurationFolderPath' to use a configuration other than ./sample-configuration.
						Specify the environment variable 'homebrew_outputFolderPath' to use an output environment other than ./output.\n
					EOF
					exit 0
				;;

				*)
					fail "Does not take any arguments except --help"
				;;

			esac
		;;

		*)
			fail "Does not take any arguments except --help"
		;;

	esac
}

depends rm awk sort cp
install_homebrew_installHomebrewPackages()
{
	rm -rf "$installedPackagesFilePath"
	
	awk '{print $3}' "$homebrew_homebrewPackagesFilePath" | sort -u >"$installedPackagesFilePath".tmp
	local package
	while IFS= read -r package
	do
		homebrew_installedBrew install "$package"
	done <"$installedPackagesFilePath".tmp
	rm -rf "$installedPackagesFilePath".tmp	
}

depends rm mkdir ln
install_homebrew_installBinarySymlinks()
{
	rm -rf "$homebrew_binFolderPath"
	mkdir -m 0700 -p "$homebrew_binFolderPath"
	
	environment_relativeSymlink "$homebrew_binFolderPath"/brew "$(pwd)"/support/homebrew-bin-wrapper
	
	local tab='	'
	local space=' '
	local ourBinaryName homebrewBinaryName homebrewPackage
	while IFS="${tab}${space}" read -r ourBinaryName homebrewBinaryName homebrewPackage
	do
		environment_relativeSymlink "$homebrew_binFolderPath"/"$ourBinaryName" "$(pwd)"/support/homebrew-bin-wrapper
	done <"$homebrew_homebrewPackagesFilePath"
}

depends cmp cp
install_homebrew_install()
{
	homebrew_installHomebrew
	
	local installedPackagesFilePath="$homebrew_installedFolderPath"/.homebrew-binaries-to-packages
	
	if [ -f "$installedPackagesFilePath" ]; then
		if [ -r "$installedPackagesFilePath" ]; then
			if cmp -s "$installedPackagesFilePath" "$homebrew_homebrewPackagesFilePath"; then
				return 0
			fi
		fi
	fi
	
	install_homebrew_installHomebrewPackages
	
	homebrew_installedBrew cleanup
	
	install_homebrew_installBinarySymlinks
	
	cp "$homebrew_homebrewPackagesFilePath" "$installedPackagesFilePath"
}

depends rm
install_homebrew_main()
{
	cd "$(_program_path_find)" 1>/dev/null 2>/dev/null
	
	. ./functions/homebrew.functions.sh
	install_homebrew_validateCommandLineArguments "$@"
	
	local homebrew_temporaryFolderPath
	local homebrew_binFolderPath
	local homebrew_homebrewVersion
	local homebrew_mirrorFolderPath
	local homebrew_cacheFolderPath
	local homebrew_installedFolderPath
	local homebrew_homebrewPackagesFilePath
	homebrew_setEnvironmentVariables "$(pwd)"
	
	install_homebrew_install
}

install_homebrew_main "$@"
